/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

apply plugin: 'elasticsearch.internal-es-plugin'
apply plugin: 'elasticsearch.internal-cluster-test'
apply plugin: 'elasticsearch.internal-yaml-rest-test'
apply plugin: 'elasticsearch.publish'

esplugin {
  name = 'x-pack-kql'
  description = 'Elasticsearch Expanded Pack Plugin - AI Flow Plugin'
  classname ='org.elasticsearch.xpack.ai-flow.AiFlowPlugin'
  extendedPlugins = ['x-pack-core']
}
base {
  archivesName = 'x-pack-ai-flow'
}

dependencies {
  compileOnly project(path: xpackModule('core'))

  testImplementation project(':test:framework')
  testImplementation(testArtifact(project(xpackModule('core'))))
}

tasks.named('yamlRestTest').configure {
  usesDefaultDistribution()
}
